# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: cul2mqtt
version: "1.0.0"
slug: cul2mqtt
description: CUL to MQTT
url: "https://github.com/siku2/hass-addon-cul2mqtt/tree/main/cul2mqtt"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
options:
  message: "Hello world..."
schema:
  message: "str?"
# image: "ghcr.io/siku2/{arch}-hass-addon-cul2mqtt"
